### ISSUE TITLE
Support no_proxy setting

### ISSUE THREAD

**Issue by roeme** [savonrb/httpi#114]
Currently, HTTPI supports setting a proxy – but not exceptions from it. This is however required for environments where a proxy is not appropriate to be used for internal hosts, but is for external ones.

Unfortunately, we cannot get around this limitation by simply using HTTPClient (which supports such settings) as the underlying adapter to HTTPI, as it seems that its HTTPI's job to set the no_proxy option: http://rubydoc.info/gems/httpclient/HTTPClient#no_proxy-instance_method , but currently doesn't.

**Comment by pcai** [comment]
It should be possible to configure this globally now, since https://github.com/savonrb/httpi/pull/237 is implemented. Thanks
