### ISSUE TITLE
Invalid version of rubyntlm in ruby 2.1.2

### ISSUE THREAD

**Issue by ddoherty03** [savonrb/httpi#127]
$ bundle show httpi
    /home/ded/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpi-2.2.5

    $ bundle show rubyntlm
    /home/ded/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rubyntlm-0.3.4

    $ ruby -v
    ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]

    $ ruby -e "require 'httpi'"
    /home/ded/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpi-2.2.5/lib/httpi/adapter    /net_http.rb:12:in `<top (required)>': Invalid version of rubyntlm. Please use v0.3.2+. (ArgumentError)
    from /home/ded/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/ded/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/ded/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpi-2.2.5/lib/httpi.rb:8:in `<top (required)>'
    from /home/ded/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    from /home/ded/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /home/ded/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from -e:1:in `<main>'

Problem appears to be that Net::NTLM::VERSION::STRING is defined by both rubyntlm gem and the ntlm-http gem.  You intend to check the former, but are getting the latter.

A look at my Gemfile.lock indicates that cucumber-standalone is dependent on web-mechanize, which depends on ntlm-http.

**Comment by coldnebo** [comment]
This is still happening with httpi 2.4.2.  Apparently mechanize 2.7.5 also pulls in ntlm-http 0.1.1.
