### ISSUE TITLE
SSL_VERSIONS match (NoMethod)

### ISSUE THREAD

**Issue by zdravko** [savonrb/httpi#142]
I am trying to load savon but immediately it throws NoMethod error in httpi/auth/ssl.rb:13:
SSL_VERSIONS = OpenSSL::SSL::SSLContext::METHODS.reject { |method| method.match /server|client/ }.sort.reverse
METHODS returns array of symbols for wich "match" wouldn't work, sort too. What happened here?
$ gem -v
1.8.24
$ ruby -v
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
$ gem list savon
savon (2.9.0)
$ gem list httpi
httpi (2.3.0)

**Comment by rogerleite** [comment]
Hi @zdravko 
I don't remember when httpi finished support to Ruby 1.8.7. Our tests are running on 1.9.x of mri and jruby (https://github.com/savonrb/httpi/blob/master/.travis.yml). This change was introduced in PR #136.

For now, you have two dirty options:

* Monkey patch Symbol and add match method
* Change httpi source to do a "to_s" before calling match.

Hope that helps and sorry for the trouble!
