### ISSUE TITLE
Link to httpi is broken on http://httpirb.com/

### ISSUE THREAD

**Issue by llimllib** [savonrb/httpi#143]
The `Code (github)` link points to `rubii/httpi` rather than `savonrb/httpi`

**Comment by tjarratt** [comment]
Thanks for bringing this up @llimllib. It's been on our radar for a while, but it just hasn't been a priority for me to fix (mostly because we're still getting issues and pull requests reported every week that require our attention). It would be nice to fix that.

**Comment by llimllib** [comment]
happy to help, is the homepage somewhere I can fix it?
