### ISSUE TITLE
Net::HTTP adapter should support more HTTP methods

### ISSUE THREAD

**Issue by lgustafson** [savonrb/httpi#152]
When using the Net::HTTP adapter, several "non-standard" HTTP methods (such as PATCH) cause exceptions to be raised when calling HTTPI#request.  The adapter only allows "standard" methods to be used.  However, in Ruby 1.9.3 and later, PATCH and other methods are officially supported in Net::HTTP.  I propose that the adapter should use reflection on Net::HTTP to determine if a specific method is available.  

PATCH in particular is frequently used in RESTful APIs so the inability to use it via HTTPI + Net::HTTP when it is supported upstream is problematic.

**Comment by rogerleite** [comment]
Hi @lgustafson! This is awesome. Open a Pull Request and i'll merge.
