### ISSUE TITLE
Unified HTTP Exceptions?

### ISSUE THREAD

**Issue by eimermusic** [savonrb/httpi#16]
I would love to have httpi catch (rescue) and re-throw all adapter exceptions so that client code (e.g. my Savon SOAP client) could be a bit cleaner in its exception handling.

A connection timeout, a connection refused, a internal server error... they are all different between the libraries and also not always in a "uniform" structure within each adapter. 

In a SOAP client I may want to distinguish all http related errors from SOAP errors and respond to them in a certain way as a group. I may want to try a backup endpoint, for example. Something I would not want to do for SOAP exceptions but which might be a good idea for timeouts and server errors.

I haven't looked at all adapters in detail to inventory the possible exceptions in full. Excon had them all nicely bundled together... about 45-48 of them it looks like. https://github.com/geemus/excon/blob/master/lib/excon/errors.rb

What do you think? Good idea? Bad idea? A lot of work?

**Comment by chetan** [comment]
Looks like this ticket can actually be closed but I was wondering why HTTPI::ConnectionError doesn't extend from HTTPI::Error like all the others do? Seems like an oversight?

https://github.com/savonrb/httpi/blob/master/lib/httpi.rb#L91

**Comment by chetan** [comment]
Ah, just realized it's a module and not a class, in order to support this usage:

https://github.com/savonrb/httpi/blob/master/lib/httpi/adapter/net_http.rb#L47-L49

Though I don't really understand the reason for this either. Why not just raise ConnectionError in the same way as the others?

**Comment by rogerleite** [comment]
Hi @chetan. 
This is really old and i don't know why this ConnectionError is a module. Maybe is something related to savon. :confused:

**Comment by tjarratt** [comment]
@chetan -- glad you brought this up.

Seems like the behavior to handle `ConnectionError` in this way came into the codebase in [December 2012](https://github.com/savonrb/httpi/commit/d1e29a9b872b38d4c24eb185dcf455070c596973). I don't think there's a strong argument to be made for doing it this way -- raising ConnectionError like you suggested seems a lot better to me. Consistency is better than clever code, in my humble opinion.

**Comment by 907th** [comment]
The reason for extending last error `$!` with a module (e.g. `ConnectionError`) is that exception can be catched with a module now:

```ruby
module ErrTrait; end
class MyErr < StandardError; end

begin
  b = MyErr.new("msg")
  b.extend ErrTrait
  fail b
rescue ErrTrait => e
  puts e.inspect # #<MyErr: msg>
end
```

`e.is_a?(ErrTrait)` returns `true` now, and `ErrTrait` acts like a common 'tag' for different kinds of exceptions.

Another solution is: reraise errors from `rescue` block using different error class. But in this case it is harder to detect original error which caused this error to happen. Luckily, there is [Exception#cause](http://blog.honeybadger.io/nested-errors-in-ruby-with-exception-cause/) since Ruby 2.1.

**Comment by pcai** [comment]
I consider this closed unless someone explains how to proceed - please see https://github.com/savonrb/httpi/issues/238. thanks
