### ISSUE TITLE
Issue with rubyntlm 0.6.0

### ISSUE THREAD

**Issue by thomasal** [savonrb/httpi#170]
I have the following error when I update rubyntlm from 0.3.2 to 0.6.0 whereas rubyntlm is not even a runtime dependencie : uninitialized constant Net::NTLM::VERSION (see more informations bellow)

I fixed it puting 

require 'net/ntlm/version'

at the beginning of my code.

A pull request may be apropriate or I am the only one having this issue ?

> 
> uninitialized constant Net::NTLM::VERSION
> c:/ruby/lib/ruby/gems/2.0.0/gems/httpi-2.4.1/lib/httpi/adapter/net_http.rb:57:in `check_net_ntlm_version!'
> c:/ruby/lib/ruby/gems/2.0.0/gems/httpi-2.4.1/lib/httpi/adapter/net_http.rb:19:in `initialize'
> c:/ruby/lib/ruby/gems/2.0.0/gems/httpi-2.4.1/lib/httpi.rb:185:in `new'
> c:/ruby/lib/ruby/gems/2.0.0/gems/httpi-2.4.1/lib/httpi.rb:185:in `load_adapter'
> c:/ruby/lib/ruby/gems/2.0.0/gems/httpi-2.4.1/lib/httpi.rb:156:in `request'
> c:/ruby/lib/ruby/gems/2.0.0/gems/httpi-2.4.1/lib/httpi.rb:127:in `get'

**Comment by rogerleite** [comment]
Hi @thomasal!

I upgraded the rubyntml version on `httpi.gemspec` file and all tests passed.
I can't look for it now, but it seems we don't have a properly test to `check_net_ntlm_version!`.

Pull requests are also welcome!

**Comment by thomasal** [comment]
I get the bug :

![image](https://cloud.githubusercontent.com/assets/9656936/15114262/fbf2d7c8-15f0-11e6-92b8-b7e17caa2973.png)


> [8] pry(main)> Net::NTLM.const_defined?(:VERSION)
> => true
> [9] pry(main)> Net::NTLM::VERSION
> NameError: uninitialized constant Net::NTLM::VERSION
> from (pry):8:in `__pry__'

something is wrong with this const_defined?

we should just remove this part :  'unless Net::NTLM.const_defined?(:VERSION)'

**Comment by mikecmpbll** [comment]
`const_defined` will search up the inheritance tree for the constant by default, you can disable this by passing false as the 2nd argument.

**Comment by thomasal** [comment]
thanks @mikecmpbll 

So we should just replace line 61 of https://github.com/savonrb/httpi/blob/master/lib/httpi/adapter/net_http.rb :

require 'net/ntlm/version' unless Net::NTLM.const_defined?(:VERSION)

by 

require 'net/ntlm/version' unless Net::NTLM.const_defined?(:VERSION, false)

I can't do a pull request right now, I'll do it later if the bug is not fixed.

**Comment by rogerleite** [comment]
👍  thanks @mikecmpbll and @thomasal
