### ISSUE TITLE
RFC: Patron adapter ownership

### ISSUE THREAD

**Issue by julik** [savonrb/httpi#172]
Hi! I am currently working on an adapter for Patron. It is now folded under the Patron repo proper. How would you like this to be integrated? The question is that it is a bit cumbersome for me to take over your `IntegrationServer` + certificate stuff, so if it stays in my repo I can't copy your integration tests for, say, Curb and just rewrite them. OTOH, if it stays in our repo (and gets tested against our test server) you do not have the responsibility to maintain it.

Should we keep the adapter in our gem and bump it every time there are changes that would have impact on it (and thus watch the major versions of HTTPI for changes), or are you willing to take it over?

**Comment by rogerleite** [comment]
Hi @julik! Sorry for this super late reply, my suggestion is to keep the adapter on your gem.

Thanks!
