### ISSUE TITLE
Exception when EventMachine is not running

### ISSUE THREAD

**Issue by sos4nt** [savonrb/httpi#173]
I have a gem that uses Savon. It is used in a project that also has EventMachine and EM-HTTP-Request in its Gemfile, but the project's EM reactor is not running.

When my gem makes a Savon connection, HTTPI attempts to use EM-HTTP-Request, which results in an error message: (because EM is not running)

```
RuntimeError: eventmachine not initialized: evma_connect_to_server
```

Wouldn't it be better to check if EM is actually available (i.e. the reactor is running) before using it?

**Comment by sos4nt** [comment]
BTW, my workaround is to set:

    HTTPI.adapter = :net_http

Maybe it would be even better to make that the default and just remove the automatic loading mechanism.

What do you think?

**Comment by rogerleite** [comment]
Hi @sos4nt!

This load mechanism is a trouble maker see https://github.com/savonrb/httpi/issues/148 for reference. I really would like to remove this from HTTPI, my fear is to break Savon and "dependent" systems. Maybe a bump to `2.5.0` could be a way.

Savon don't allow to define an adapter manually?

Hope that helps.
