### ISSUE TITLE
Rack dependency too loose

### ISSUE THREAD

**Issue by mcloonan** [savonrb/httpi#176]
In the gemspec:

```
s.add_dependency 'rack'
```

The newest version of rack requires ruby 2.2.2 or greater; older versions of rack had no requirement.

This is an issue because for the Google DFP library, for example:

```
gem install google-dfp-api
```

This has a dependency on httpi. If you're using an older version of Ruby, say 2.0, you get a warning saying that you need 2.2.2 or greater for rack. But you really don't; if you manually install rack 1.6.4 beforehand, then you can install httpi just fine, because that version is also compatible with httpi.

Can you add a dependency on rack 1.6.4 if you don't need the new features so that libraries that require httpi can still support previous versions of Ruby without having to manually install a specific version of Rack beforehand?

**Comment by rogerleite** [comment]
Hi @mcloonan!

I have no problem to set this on Gemfile, if `rack` 1.6.4 is compatible. Would you mind to send a Pull Request with this change?

Thanks
