### ISSUE TITLE
HTTPI (net_http) request failed in Rails

### ISSUE THREAD

**Issue by mid9commander** [savonrb/httpi#178]
My request works well in a script where I only include httpi and savon, but once I include it into a Rails application it seems to just time out.  Is there anything I should be aware of when it comes to the HTTP settings in Rails?

HTTPI::Adapter.use = :net_http
client = Savon::Client.new do |wsdl, http|
  wsdl.document = base_path
  http.auth.ntlm('user', '', 'pass')
  http.auth.ssl.verify_mode = :none
end

client.wsdl.soap_actions  (this is the line that it will time out, the last debug message I see is 

D, [2016-11-10T00:39:53.487483 #1] DEBUG -- : HTTPI executes HTTP GET using the net_http adapter)

I am using this in a dockerized environment btw.

**Comment by mid9commander** [comment]
Never mind, it was ruby-ntlm 0.0.3 that is breaking it.

**Comment by rogerleite** [comment]
👍  👀
