### ISSUE TITLE
Proxy password with '@' character is not supported

### ISSUE THREAD

**Issue by achiinto** [savonrb/httpi#179]
I have a proxy credential that has '@' in the password. If I don't escape, it will fail at parsing the URI. If I escape the '@', the code does not seems to unescape it. 

My test is hitting code in this part and failing, in httpi/adapter/net_http.rb:73
```
      def create_client
        proxy_url = @request.proxy || URI("")
        if URI(proxy_url).scheme == 'socks'
          proxy =Net::HTTP.SOCKSProxy(proxy_url.host, proxy_url.port)
        else
          proxy = Net::HTTP::Proxy(proxy_url.host, proxy_url.port, proxy_url.user, proxy_url.password)
        end
        proxy.new(@request.url.host, @request.url.port)
      end
```
How should I approach using this for proxy like 'username:password@host:port' with '@' in the password?

Thanks,

**Comment by mikecmpbll** [comment]
try the URL encoded version of `@`, %40.

**Comment by rogerleite** [comment]
Like @mikecmpbll said, you can try https://en.wikipedia.org/wiki/Percent-encoding

**Comment by achiinto** [comment]
I have been trying that encoding for all day already. The account with such password did not work with the %40 encoding, but proven to be working on other web application written in PHP and C#. Kind of pain when I am trying hard to introduce the team to Ruby.

**Comment by rogerleite** [comment]
@achiinto in this case my suggestion is to use `net_http` direct, see https://github.com/augustl/net-http-cheat-sheet/blob/master/proxy.rb#L20 for example. This way we can check if is a bug on ruby or httpi.

What ruby version are you using? You tried to use `http_proxy` environment variable? Maybe this way can support the escaped string? Example: https://github.com/augustl/net-http-cheat-sheet/blob/master/proxy.rb#L7

**Comment by achiinto** [comment]
Hi @rogerleite, I actually already did tried modifying the code in this gem and hardcoded the password in it. Although there is still a chance that the proxy credential issue could be from my company complicated setup, but my server could use certain service account to access the proxy but not with the account that has the '@' (while this account with '@' in password still work on other servers with C# code or PHP). 

With Net::Http, it still does not work. I am using ruby 2.3.1. And I believe I have seen this behavior previously with ruby 2.1.2.

Thanks for the cheat sheet. A lot of good info there. I have tried the ENV['http_proxy'] with this...
```
request = Net::HTTP::Get.new(uri.request_uri)
response = http.request(request)
```
But it does not work with the credential that should have worked (the one without '@' in password.)
While the same credential withtout the '@', worked with ....
```
Net::HTTP.start(uri.host, uri.port, proxy_uri.host, proxy_uri.port, 'proxy_user', 'proxy_pass')
...etc
```
And either ways failed the authentication or the URI formatting with the '@' or the '#40'.

Not sure if anyone can reproduce this. And likely anyone would just reset their password to one without '@' or getting another account. Personally, I was stuck with the password as the credential is being used by other PHP and C# applications. Anyhow, I have gotten an IP based proxy bypass setup, So, I no longer require using the credential. But, if you think this is worth looking at, I can try investigate longer. it just sad to tell others in the team that the password works with C# and PHP, but not Ruby...

By the way, it was me using Savon that got me looking at this issue.

**Comment by rogerleite** [comment]
Don't be sad, this is a specific scenario, don't blame Ruby. 

```
Ruby is...
A dynamic, open source programming language with a focus on simplicity and productivity.
It has an elegant syntax that is natural to read and easy to write.
```
https://www.ruby-lang.org/en/

If team don't see value on **simplicity** and **productivity**, it'll be very hard to adopt it.

Keep coding, good job @achiinto!
I'm closing this issue for now, feel free to comment.
