### ISSUE TITLE
Httpi::Adapter::HTTP references ::HTTP ..?  Shouldn't that be Net::HTTP?

### ISSUE THREAD

**Issue by patrick99e99** [savonrb/httpi#184]
Experiencing an issue where I have my own namespaced HTTP module in my project:

    module FancyModule
      module HTTP; end
    end

And when rails autoloads code that uses savon + autoloads lib/**, it gets confused and blows up saying:

LoadError - Unable to autoload constant HTTP, expected /Users/patrick/my_project/lib/fancy_module/http.rb to define it:
  activesupport (4.2.8) lib/active_support/dependencies.rb:495:in `load_missing_constant'
  activesupport (4.2.8) lib/active_support/dependencies.rb:184:in `const_missing'
  httpi (2.4.2) lib/httpi/adapter/http.rb:61:in `create_client'
  httpi (2.4.2) lib/httpi/adapter/http.rb:24:in `initialize'
  httpi (2.4.2) lib/httpi.rb:185:in `load_adapter'
  httpi (2.4.2) lib/httpi.rb:156:in `request'
  httpi (2.4.2) lib/httpi.rb:133:in `post'
  savon (2.11.1) lib/savon/operation.rb:94:in `block in call_with_logging'
  savon (2.11.1) lib/savon/request_logger.rb:12:in `log'
  savon (2.11.1) lib/savon/operation.rb:94:in `call_with_logging'
  savon (2.11.1) lib/savon/operation.rb:54:in `call'
  savon (2.11.1) lib/savon/client.rb:36:in `call'

...

Just am wondering why this line:
https://github.com/savonrb/httpi/blob/master/lib/httpi/adapter/http.rb#L32

is referencing some magical top level HTTP constant?  What is this?  This I assume is meant to reach Net::HTTP?

**Comment by AaronM04** [comment]
I would also like to know. I get a slightly different error in a non-rails project:

```
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/httpi-2.4.2/lib/httpi/adapter/http.rb:61:in `create_client': uninitialized constant HTTP (NameError)
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/httpi-2.4.2/lib/httpi/adapter/http.rb:24:in `initialize'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/httpi-2.4.2/lib/httpi.rb:185:in `new'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/httpi-2.4.2/lib/httpi.rb:185:in `load_adapter'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/httpi-2.4.2/lib/httpi.rb:156:in `request'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/httpi-2.4.2/lib/httpi.rb:127:in `get'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/wasabi-3.5.0/lib/wasabi/resolver.rb:43:in `load_from_remote'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/wasabi-3.5.0/lib/wasabi/resolver.rb:33:in `resolve'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/wasabi-3.5.0/lib/wasabi/document.rb:142:in `xml'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/wasabi-3.5.0/lib/wasabi/document.rb:160:in `parse'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/wasabi-3.5.0/lib/wasabi/document.rb:147:in `parser'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/wasabi-3.5.0/lib/wasabi/document.rb:64:in `soap_actions'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/savon-2.11.1/lib/savon/operation.rb:22:in `ensure_exists!'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/savon-2.11.1/lib/savon/operation.rb:15:in `create'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/savon-2.11.1/lib/savon/client.rb:32:in `operation'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/savon-2.11.1/lib/savon/client.rb:36:in `call'
```

**Comment by rogerleite** [comment]
Hi @patrick99e99 and @AaronM04 

This magical top level HTTP constant is the [http gem](https://github.com/httprb/http), one of the gems that HTTPI supports as adapter.

This seems to be a bug with load order of adapters and the common namespace `HTTP`. HTTPI is trying to use `http` adapter because of loaded namespace `HTTP`. [Example](https://github.com/savonrb/httpi/blob/master/lib/httpi/adapter.rb#L16):

```ruby
LOAD_ORDER = [:httpclient, :curb, :em_http, :excon, :http, :net_http, :net_http_persistent]
```

I think if you install one of these gems: `httpclient`, `curb` or `excon` fixes this error. Do you have one of these gems on your Gemfile and required?

Hope that helps.
Cheers.

**Comment by AaronM04** [comment]
@rogerleite My problem is solved -- there was an extra http file in the repository with `module Http` inside it. Deleting that fixed the issue.

Thank you so much!

**Comment by patrick99e99** [comment]
@rogerleite no..  do not have any of those gems in my project.  I was able to get around this by removing lib/** from the rails auto load path, and just manually requiring the files in lib (which was unfortunate to have to do).
