### ISSUE TITLE
openssl CA  cant‘t  solution 

### ISSUE THREAD

**Issue by lightmaya** [savonrb/httpi#185]
HTTPI::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
from /home/snd/.rvm/gems/ruby-2.1.1/gems/httpi-2.4.2/lib/httpi/adapter/net_http.rb:51:in `rescue in request'

**Comment by rogerleite** [comment]
Hi @lightmaya 
I need more information to try to help. What is your environment, url and etc.

**Comment by lightmaya** [comment]
@rogerleite   3Q  RedHat 7.2 calls the WebService interface error reporting, has been resolved in the savon to join ssl_verify_mode:: None
