### ISSUE TITLE
HTTPI (at least with default adapter) doesn't automatically send basic auth headers

### ISSUE THREAD

**Issue by novalis** [savonrb/httpi#186]
I'm using HTTPI with the default adapter.
```
request = HTTPI::Request.new(url: url)
request.auth.basic(username, password)
HTTPI.get(request)
```
This sends a request *without* an Authorization header.  When it gets a 401 back, then it sends the Authorization header.  This wastes round-trips.  Instead, it should send the Authorization header on the first request.

**Comment by rogerleite** [comment]
Hi @novalis 

In theory, curb adapter sets basic credentials. Spec [here](https://github.com/savonrb/httpi/blob/master/spec/httpi/adapter/curb_spec.rb#L192) and source [here](https://github.com/savonrb/httpi/blob/master/lib/httpi/adapter/curb.rb#L67).
I suspect that username [is not set](https://github.com/savonrb/httpi/blob/master/lib/httpi/adapter/curb.rb#L92), specs don't cover it.

I'm alone with httpi and I don't have time to see this now. Would you mind to check and open a pull request?

Thanks.

**Comment by novalis** [comment]
I'm sorry.  This is my fault -- I thought I has configured the curb adapter, but in fact, I had not.  So the default adapter has this problem, but the 'curb' adapter works correctly.  I guess this is still a bug, but it is no longer a bug which affects me, because I need to use the curb adapter.

**Comment by rogerleite** [comment]
No problem. By default httpi use adapter based on installed gem and [load order](https://github.com/savonrb/httpi/blob/master/lib/httpi/adapter.rb#L16), maybe you were using some adapter without basic auth support. 👍
