### ISSUE TITLE
Deprecation warning in ruby 2.5

### ISSUE THREAD

**Issue by tycooon** [savonrb/httpi#188]
Hi, I'm getting a deprecation warning:
`
lib/ruby/gems/2.5.0/gems/httpi-2.4.2/lib/httpi/auth/ssl.rb:13: warning: constant OpenSSL::SSL::SSLContext::METHODS is deprecated
`

**Comment by rogerleite** [comment]
Hi @tycooon! Thanks for the issue. 

Unfortunately, HTTPI is a low priority for me now. Feel free to send a pull request, just remember to update travis ci with the new version and also support old ruby versions.

Thanks,
Roger Leite

**Comment by espen** [comment]
https://github.com/ruby/openssl/commit/5653599e150bd92d8631858fe6e0def1f9a3c33d

> OpenSSL::SSL::SSLContext::METHODS, which contained the possible names of
SSL methods, is not useful anymore. It is now deprecate_constant-ed.

Apparently it's not useful 🤣 

Replace it with the current generated list?
`[:TLSv1_2, :TLSv1_1, :TLSv1, :SSLv3, :SSLv23, :SSLv2]`

As for now it's just a warning, it doesn't say anything when it will be removed though.

**Comment by webhoernchen** [comment]
Pull request #189  added.

**Comment by maxrep66** [comment]
how can i replace spen with that list Replace it with the current generated list?
[:TLSv1_2, :TLSv1_1, :TLSv1, :SSLv3, :SSLv23, :SSLv2] how can i do it??? help me pls
