### ISSUE TITLE
Diese Präsenz ist derzeit nicht verfügbar.

### ISSUE THREAD

**Issue by kwerle** [savonrb/httpi#193]
Doc link http://httpirb.com/ -> Diese Präsenz ist derzeit nicht verfügbar.

My German isn't all that great, but I'm pretty sure the site is down/missing.

**Comment by pcai** [comment]
thanks. i pushed commit https://github.com/savonrb/httpi/commit/345e5e2b1a4376a7be769f67088a431895de09ad to remove references to the broken site (we haven't had control of that domain for multiple years now).
