### ISSUE TITLE
TLSv1_3 parameter support for ssl_version

### ISSUE THREAD

**Issue by HLFH** [savonrb/httpi#199]
Hi,

It would be great to support TLS 1.3 since it is now a standard.

Thanks,
Gaspard

**Comment by rogerleite** [comment]
Hi @HLFH.

Thanks for the feedback, unfortunately I'm out of time to work on HTTPI, sorry.
I can help on code review, feel free to send us a pull request.

Regards,
Roger Leite

**Comment by pcai** [comment]
hi @HLFH can you provide a case where TLS 1.3 isn't supported?

**Comment by pcai** [comment]
please reopen with requested info if you still think this is an issue
