### ISSUE TITLE
Enforce IPv6 use?

### ISSUE THREAD

**Issue by HLFH** [savonrb/httpi#200]
Hi,

I don't know if IPv6 is supported and how. I would like to do SOAP requests and enforce IPv6 connection to a WebService that supports both IPv4 and IPv6. 

With a parameter like:

> ip_version: :IPv6

**Comment by ioquatix** [comment]
This is a network level concern.

**Comment by pcai** [comment]
As @ioquatix mentioned you can usually address ipv6 preference at the network layer. At the application layer httpi operates at, some adapters may have address resolution settings that affect the preference of entries returned from (e.g.) `Socket.getaddrinfo` in dual stack to prefer ipv6 first, but considering https://github.com/savonrb/httpi/issues/238 adding support for this would be considered out of scope for httpi. Sorry
