### ISSUE TITLE
How can we define the environment for mounted rails apps

### ISSUE THREAD

**Issue by AJFaraday** [savonrb/httpi#207]
Sorry if this is the wrong place to ask this, but I can't find any documentation about it.

I'm mounting an app with the HTTPI Rack adapter:

```ruby
::HTTPI.adapter = :rack
::HTTPI::Adapter::Rack.mount 'app', ::MyApp::Application
```

However, it's starting up in development mode, which may be the root of a problem. 

I've tried a few different approaches to set the environment before mounting 

```ruby
`export RAILS_ENV=production`
Rails.env = 'production'
Rails.env = 'PRODUCTION'
```

None of these seem to have worked so far.

**Comment by rogerleite** [comment]
Hi @AJFaraday 

The short answer is I don't know how to set the environment for your case. The only documentation this adapter has is the PR that implemented: https://github.com/savonrb/httpi/pull/75.

What's your root problem? What do you want to do with this?
The idea of this adapter is using to test only I think.

Hope that helps.

**Comment by AJFaraday** [comment]
@rogerleite The issue is occurring in testing, when a value in one of the arguments contains a % symbol. 

```
/home/biorails/.rvm/rubies/ruby-2.2.10/lib/ruby/2.2.0/uri/common.rb:382:in `decode_www_form_component': invalid %-encoding ("1.0" encoding="ISO-8859-1"?><en
```

It doesn't seem to be reaching the controller, the call doesn't hit the logs.

It's fine when I pass the exact XML to a production server there's no error.

---

The environment was the only change I could see.

**Comment by pcai** [comment]
@AJFaraday sorry - I think you'll have better luck trying to ask this in a rails-specific forum. The rack adapter is very simple and doesn't really have any configuration options
