### ISSUE TITLE
Optional dependency rack used internally

### ISSUE THREAD

**Issue by tbolender** [savonrb/httpi#229]
Thanks for your work on this gem! We notice the following error on all non-Rails usages after the update to version 3.0.0:

```
/app/vendor/bundle/ruby/2.7.0/gems/httpi-3.0.0/lib/httpi/request.rb:4:in `require': cannot load such file -- rack/utils (LoadError)
	from /app/vendor/bundle/ruby/2.7.0/gems/httpi-3.0.0/lib/httpi/request.rb:4:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.7.0/gems/httpi-3.0.0/lib/httpi.rb:4:in `require'
	from /app/vendor/bundle/ruby/2.7.0/gems/httpi-3.0.0/lib/httpi.rb:4:in `<top (required)>'
```

I noticed that you made rack an optional dependency, but seem to treat it internally as mandatory. I would be glad to have the reference either removed or as an actual dependency set (that it seems to be?).

**Comment by olleolleolle** [comment]
Yeah, the smoothest way would probably be to upgrade it to be a... real runtime dependency: https://github.com/savonrb/httpi/search?q=Utils 

HeaderHash class and something about building URLs.

**Comment by tbolender** [comment]
Here you go. Would be nice to have that as soon as possible out there :)
