### ISSUE TITLE
HTTPi fails with https endpoint

### ISSUE THREAD

**Issue by Toucouleur66** [savonrb/httpi#231]
I created a issue https://stackoverflow.com/questions/70853629/sslerror-certificate-has-expired-while-using-httpi

using `httpi` 2.4 may be not eougut

I tried to install gem with `httpi (~> 3.0.0)`but for now

```
    overpass-api-ruby was resolved to 0.3.1, which depends on
      httpi (~> 2.4)
```

For now I have always

`HTTPI::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired))`

whenever I try to change the endpoint for a secured one such as https://maps.mail.ru/osm/tools/overpass/api/interpreter

**Comment by olleolleolle** [comment]
@Toucouleur66 In order for the issue to be fixed in Overpass Ruby API library, I suggest you make a PR to that project: https://github.com/BrunoSalerno/overpass-api-ruby

**Comment by pcai** [comment]
@Toucouleur66 please reopen if you can include a reproduction pointing to httpi as the source of the issue. thanks!
