### ISSUE TITLE
Rack::Utils::HeaderHash --> Rack::Headers

### ISSUE THREAD

**Issue by Nathan-Yorio** [savonrb/httpi#239]
This in `request.rb` is deprecated syntax according to my builds. 
 
 ``` ruby
  # Returns a Hash of HTTP headers. Defaults to return an empty Hash.
  def headers
    @headers ||= Rack::Utils::HeaderHash.new
  end

  ```
    
  ```
  Rack::Utils::HeaderHash is deprecated and will be removed in Rack 3.1, switch to Rack::Headers
  ```

**Comment by pcai** [comment]
fixed in https://github.com/savonrb/httpi/commit/56cd67bf0da61c39552be1d9fc9bff6f33315284

**Comment by mvz** [comment]
This breaks compatibility with Rack 2 so httpi should not allow that version of rack anymore.
