### ISSUE TITLE
improve how we're logging

### ISSUE THREAD

**Issue by rubiii** [savonrb/httpi#74]
currently, you can change `HTTPI.log_level` to change the log level we are using to log.
if you look at [HTTPI.log](https://github.com/savonrb/httpi/blob/master/lib/httpi.rb#L170), it sends the `log_level` to the Logger.

that's actually what the Logger's severity should be used for. what i did for savon 2.0 (which used the same method before), was to just [log with an appropriately low log level](https://github.com/savonrb/savon/blob/v2.0.2/lib/savon/request.rb#L91) like "debug" or "info" and let people [change the Logger's severity](https://github.com/savonrb/savon/blob/v2.0.2/lib/savon/options.rb#L156) to specify what they want to see.

**Comment by pcai** [comment]
Closing - please see https://github.com/savonrb/httpi/issues/238. thanks
