### ISSUE TITLE
More adapters

### ISSUE THREAD

**Issue by minad** [savonrb/httpi#76]
Is there any reason why httpi doesn't support the following libraries:
- <del>Httparty</del>
- <del>Patron</del>
- Typhoeus
- Excon

**Comment by coldnebo** [comment]
Just FYI: we just got a potential requirement for typhoeus.

The use case is issuing multiple service requests in parallel to increase performance.

concurrent-ruby exists in Rails5, but I'm not clear on how deeply integrated it is... but it might be nice to use DataFlow to figure out whether calls can be sequential or parallel simply by looking at the data used from one call to the next.  In theory, this gives better performance than always requiring sequential service calls.

We average 5 or so service requests per page, so it's quite service intensive.  We are also looking at caching as much state as possible (perhaps client-side/Redux?), but that is also complicated to manage.

I'm on the lookout for solutions in this space, but also would consider implementing a driver for a pull request if httpi wants to go in this direction.
